import globals from 'globals';
import js from '@eslint/js';
import stylisticJs from '@stylistic/eslint-plugin';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
            },
            ecmaVersion: 'latest',
            sourceType: 'module',
        },
        plugins: {
            '@stylistic': stylisticJs
        },
        rules: {
            // possible problems
            'array-callback-return': 2,
            'no-await-in-loop': 2,
            'no-constructor-return': 2,
            'no-duplicate-imports': 2,
            'no-promise-executor-return': 2,
            'no-self-compare': 2,
            'no-template-curly-in-string': 2,
            'no-unmodified-loop-condition': 2,
            'no-unreachable-loop': 2,
            'no-use-before-define': [2, 'nofunc'],
            'require-atomic-updates': 2,

            // suggestions
            'accessor-pairs': 2,
            'arrow-body-style': 2,
            'camelcase': 2,
            'consistent-return': 2,
            'dot-notation': 2,
            'eqeqeq': [2, 'smart'],
            'func-name-matching': 2,
            'grouped-accessor-pairs': 2,
            'new-cap': 2,
            'no-array-constructor': 2,
            'no-caller': 2,
            'no-else-return': 2,
            'no-extend-native': 2,
            'no-extra-bind': 2,
            'no-extra-label': 2,
            'no-invalid-this': 2,
            'no-iterator': 2,
            'no-labels': 2,
            'no-lone-blocks': 2,
            'no-lonely-if': 2,
            'no-loop-func': 2,
            'no-new': 2,
            'no-new-wrappers': 2,
            'no-object-constructor': 2,
            'no-proto': 2,
            'no-return-assign': 2,
            'no-sequences': 2,
            'no-throw-literal': 2,
            'no-undef-init': 2,
            'no-unneeded-ternary': 2,
            'no-unused-expressions': 2,
            'no-useless-call': 2,
            'no-useless-computed-key': 2,
            'no-useless-concat': 2,
            'no-useless-constructor': 2,
            'no-useless-escape': 2,
            'no-useless-rename': 2,
            'no-useless-return': 2,
            'no-var': 2,
            'no-void': 2,
            'no-with': 2,
            'object-shorthand': 2,
            'prefer-arrow-callback': 2,
            'prefer-const': 2,
            'prefer-promise-reject-errors': 2,
            'prefer-rest-params': 2,
            'prefer-spread': 2,
            'prefer-numeric-literals': 2,
            'prefer-template': 2,
            'prefer-regex-literals': 2,
            'require-await': 2,
            'strict': 2,
            'yoda': 2,

            // stylistic
            '@stylistic/indent': [2, 4, {flatTernaryExpressions: true}],
            '@stylistic/array-bracket-spacing': 2,
            '@stylistic/arrow-parens': [2, 'as-needed', {requireForBlockBody: true}],
            '@stylistic/arrow-spacing': 2,
            '@stylistic/block-spacing': 2,
            '@stylistic/brace-style': [2, '1tbs', {allowSingleLine: true}],
            '@stylistic/comma-spacing': 2,
            '@stylistic/comma-style': 2,
            '@stylistic/computed-property-spacing': 2,
            '@stylistic/dot-location': [2, 'property'],
            '@stylistic/eol-last': 2,
            '@stylistic/function-call-spacing': 2,
            '@stylistic/key-spacing': 2,
            '@stylistic/keyword-spacing': 2,
            '@stylistic/new-parens': 2,
            '@stylistic/no-mixed-spaces-and-tabs': 2,
            '@stylistic/no-trailing-spaces': 2,
            '@stylistic/no-whitespace-before-property': 2,
            '@stylistic/object-curly-spacing': 2,
            '@stylistic/operator-linebreak': [2, 'after'],
            '@stylistic/quotes': [2, 'single'],
            '@stylistic/linebreak-style': [2, 'unix'],
            '@stylistic/semi': [2, 'always'],
            '@stylistic/semi-spacing': 2,
            '@stylistic/generator-star-spacing': 2,
            '@stylistic/rest-spread-spacing': 2,
            '@stylistic/yield-star-spacing': 2,
            '@stylistic/template-tag-spacing': 2,
            '@stylistic/no-confusing-arrow': 2,
            '@stylistic/implicit-arrow-linebreak': 2,
            '@stylistic/space-before-blocks': 2,
            '@stylistic/space-before-function-paren': [2, {anonymous: 'always', named: 'never'}],
            '@stylistic/space-in-parens': 2,
            '@stylistic/space-infix-ops': 2,
            '@stylistic/space-unary-ops': 2,
            '@stylistic/switch-colon-spacing': 2
        }
    }
];
